import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar"
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Anime Ranger X",
  description: "Generated by BoatMousay",
  icons: {
    icon: "/favicon.ico",         // สำหรับ favicon ทั่วไป
    shortcut: "/favicon.ico",     // สำหรับ shortcut บางระบบ
    apple: "/apple-touch-icon.png", // สำหรับ iOS (optional)
  },
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <Navbar />
        {children}
      </body>
    </html>
  );
}
